effector/effector

packages/effector-react/index.d.ts, packages/effector/index.d.ts
Hope adding [new type parameter](https://github.com/miyaokamarina/effector/blob/c9091c666852c7eb2dacbf61240fe5a3d9d2cd72/packages/effector/index.d.ts#L55) won’t break anything, lol.
=> Fix TypeScript bindings

src/react/useStore.js
```js
const $isModalOpened = $modals.map(modals => modal => modals.includes(modal))
$isModalOpened.watch(console.log)
// modal => modals.includes(modal)
const isModalOpened = useStore($isModalOpened)
console.log(isModalOpened)
// modal => modals.includes(modal)
// false
```
=> Fixed work of hook with function values in stores

CODE_OF_CONDUCT.md
=> CODE OF CONDUCT

src/index.js
=> add description

src/store/__tests__/diamond-deps.test.js
add real world test for diamond dependencies computation
=> add "display name" test

src/react/useStore.js
=> useStore: remove useStoreFast

src/react/useStore.js
fixes: https://codesandbox.io/s/y21jj6l8n9
=> useStore: return store state instead of react state

README.md
Add a Patreon icons to the header.
=> docs(reamde): add a patreon icons to the header

website/try/view.js
=> fix(website): don't lint JSON

.gitpod.yml
https://www.gitpod.io/docs/44_Config_Start_Tasks/
=> gitpod/config/mod: init and tests start

packages/effector/index.d.ts
=> TS typings for effect.map

packages/effector/index.d.ts
=> TS typing for sample

docs/api/effector-react/createComponent.md, docs/api/effector-react/useStore.md, examples/effector-react-example/src/store.js
I'm  fixed only what I can understand, no more.  With love ❤
=> Small fixes in docs

docs/api/effector/sample.md, website/client/i18n/en.json, website/client/sidebars.json
`sample` method documentation, examples added
=> sample docs added

docs/api/effector/Store.md
Change description in Store example 4
=> Small fixes in doc

docs/api/effector/Store.md
swapped arguments delay and param
`setTimeout(code, delay, param1, param2)`
=> Example with Effect

docs/api/effector/Store.md
added documentation about `.thru` method in Store.
=> docs changes

docs/api/effector/merge.md, docs/api/effector/split.md, website/client/i18n/en.json, website/client/sidebars.json
`merge` documentation enrichment, `split` documentation added
=> Split docs added, merge docs changes

docs/api/effector/Store.md, docs/api/effector/sample.md
This removes broken links of `Unit`.
closes #140
---
<details>
<summary>
</summary>
- [#140: Remove broken link to Unit in sample documentation](https://issuehunt.io/repos/123197392/issues/140)
---
</details>
=> [docs] Remove broken links

docs/recipes/usage-with-typescript.md
Add usage with typescript 
Fix #145
---
<details>
<summary>
</summary>
- [#145: Usage with TypeScript is missing](https://issuehunt.io/repos/123197392/issues/145)
---
</details>
=> #145 Add section usage with Typescript

docs/recipes/usage-with-typescript.md
After conneting to github repo, sandbox link was changed, update it in article
=> Fix sandbox link in article

docs/api/effector/Store.md, docs/glossary.md
---
<details>
<summary>
</summary>
- [#163: Missing store.updates in documentation](https://issuehunt.io/repos/123197392/issues/163)
---
</details>
=> #163 Add docs for `Store.updates` event

docs/api/effector-react/index.md, docs/api/effector-react/useList.md, website/client/sidebars.json
---
<details>
<summary>
</summary>
- [#171: Missing useList in documentation](https://issuehunt.io/repos/123197392/issues/171)
---
</details>
=> useList documentation

docs/recipes/react/example-forms.md, website/client/i18n/en.json, website/client/sidebars.json
And usage of `getState` with replacement in favor of `sample` too!
=> Examples of usage with forms in React added

src/react/__tests__/createComponent.test.js, src/react/createComponent.js
---
<details>
<summary>
</summary>
- [#183: `createComponent` not supporting hooks yet](https://issuehunt.io/repos/123197392/issues/183)
---
</details>
=> createComponent hooks

docs/api/effector-vue/ComponentOptions.md, docs/api/effector-vue/Vue.md, docs/api/effector-vue/VueEffector.md
---
<details>
<summary>
</summary>
- [#141: effector-vue documentation is missing](https://issuehunt.io/repos/123197392/issues/141)
---
</details>
=> effector-vue docs

CHANGELOG.md, packages/effector-vue/package.json, tools/builder/packages.config.js
---
<details>
<summary>
</summary>
- [#197: Vue-effector, passing shape of stores fails with error](https://issuehunt.io/repos/123197392/issues/197)
---
</details>
=> effector-vue 20.2.0

website/client/core/Footer.js
=> Fix logo size in footer

docs/api/effector/sample.md
I think it's pretty important use-case, especially if we're trying to render from multiple stores, it can save us some render cycles
=> [docs] Adds case with single store argument to sample.md

docs/recipes/react/dynamic-form-schema.md, docs/recipes/react/dynamic-form.md
Honestly, I think we should give more explanations for this example. But I don't have that opportunity at work yet, but I don't want to lose it or forget it.
=> docs: Add example with dynamic form

docs/api/effector-vue/createComponent.md, docs/api/effector-vue/index.md
=> updated docs

packages/effector-vue/index.d.ts
=> fix: type typo

docs/api/effector/combine.md
With `?`, I'm trying to show you that the function is not necessary.
=> Docs: update combine docs

docs/api/effector/sample.md
objects and arrays with stores in sample source
=> docs(sample): add docs for

docs/api/effector/index.md
Updated top-level exports with couple features from the sidebar
=> Improve doc visibility for mobile

website/client/docusaurus.config.js, website/client/src/css/custom.css
Change prism theme to vsDark
Increase css var  `code-font-size` to 95%
=> Change theme. Increase code-font-size

docs/advanced-guide/Computation priority.md, website/client/sidebars.js
=> add Advanced guide

docs/api/effector/Event.md
Fixing the variable name which I assume was a typo
=> Minor change in docs

package-lock.json, packages/@effector/babel-plugin/package.json, packages/@effector/forms/package.json, packages/bs-effector/package.json, packages/effector-dom/index.d.ts, src/dom/__tests__/index.test.ts, src/dom/h.ts, src/dom/render/h.ts, src/dom/render/index.h.ts
When we configure a handler for a tag we can set preventDefault and stopPropagation functions.
```js
const click = createEvent()
/* Before: */
click.watch(e => e.preventDefault())
h('button', () => {
handler({passive: false}, {click})
spec({text: 'Click me'})
})
/* After: */
h('button', () => {
handler({prevent: true /* also you could set `stop: true` from stopPropagation  */}, {click})
spec({text: 'Click me'})
})
```
=> added [stop] and [prevent] property for configure listener from [handler]

docs/introduction/installation.md, website/client/docusaurus.config.js, website/client/package.json, website/client/src/components/Code/Code.js, website/client/src/components/Code/index.js, website/client/src/pages/index.js, website/client/src/pages/styles.module.css, website/client/yarn.lock
- up version
- add light theme for code
- back example on main page
- change sh to bash in docs for right display of highlights
=> [Docusaurus] improvs and fixs

website/client/src/pages/index.js, website/client/src/pages/styles.module.css
A slight modification of the features section, for greater aesthetics
=> change feature title align, and feature image icon

src/effector/createEffect.js
Main thing I want to change here → preserve _any_ fields in result in events `done` and `fail`.
I don't know if you are ok with destructuring assignment syntax, if no — feel free to reject or ask for changes :)
=> Small Effect changes

website/client/src/pages/index.js
Slightly updated code example, in the old version it was not obvious that reducer functions actually works:
```javascript
add(2)
// → counter: 2
sub(1)
// → counter: 1
```
looks like event just passes value to the store.
I changed so it should be more clear:
```javascript
add(5)
// → counter: 5
sub(1)
// → counter: 4 ← now we see that reducer actually works
```
=> Update code example

src/effector/createUnit.js
Maybe inequality operator not needed there? 🧐
=> remove inequality operator

docs/api/effector/Store.md
=> fix store watch document

docs/recipes/react/example-forms.md
=> Fix form submit

docs/api/effector/index.md, docs/api/effector/sample.md
TODO Decide if more examples are needed
TODO Decide if `greedy` needed in docs
=> Sample docs rewrite

website/client/blog/2019-02-24-Media-queries-with-effector.md, website/client/blog/2019-05-25-Custom-i18n-solution-with-effector.md, website/client/docusaurus.config.js, website/client/package.json, website/client/src/css/custom.css, website/client/yarn.lock
* update dependencies
* edit blog arcticles
* remove darkTheme.js
* Close #332
=> [Docusaurus]: improvements and edits

packages/forest/README.md
Added simple Login form as Forest usage example.
=> Update Forest usage example

src/effector/__tests__/region.test.js
Refactor "difference in behavior with domains" tests for `withRegion`
=> Refactor some region tests

docs/api/effector/hydrate.md
=> Add warning about hydration requiring initialized stores

website/client/sidebars.js
Added missed page for effector-vue
=> added gate page for effector-vue API

docs/api/effector/babel-plugin.md, src/babel/__tests__/__snapshots__/babel-plugin.test.js.snap, src/babel/__tests__/babel-plugin.test.js, src/babel/__tests__/fixtures/factories-without-name.js, src/babel/__tests__/fixtures/factories-without-name.options.json, src/babel/__tests__/fixtures/units-without-name.js, src/babel/__tests__/fixtures/units-without-name.options.json, src/babel/babel-plugin.js
=> add `addNames` option for babel-plugin, by default `true` #446

packages/effector/index.d.ts, src/types/__tests__/effector/sample/arrayTarget.test.ts, src/types/__tests__/effector/sample/clockArray.test.ts, src/types/__tests__/effector/sample/sample.test.ts
=> Refactor sample types

packages/effector/index.d.ts, src/types/__tests__/effector/sample/arrayTarget.test.ts, src/types/__tests__/effector/sample/clockArray.test.ts, src/types/__tests__/effector/sample/generated/arrayTargetGen.test.ts, src/types/__tests__/effector/sample/sample.test.ts
fix target unit replacement,
fix clock without source,
fix IfAssignable helper,
fix type inference of events returned from map/filter/merge
=> Improve sample types

packages/effector/index.d.ts
=> add domain createStore updateFilter type

packages/effector/index.d.ts, src/types/__tests__/effector/createApi.test.ts
=> fix return type of reducer for createApi

src/vue/__tests__/createGate.test.ts, src/vue/__tests__/optionsApi.test.ts, src/vue/lib/deepEqual.ts, src/vue/optionsApi.ts, src/vue/useStore.ts, src/vue/useVModel.ts
thanks, @Spoki4 for reproduce bug with useGate
WIP: support vue 3 options api. Need to:
- write docs
- types
=> fixed bug with useGate position related to useStore and useVModel

website/client/i18n/ru/docusaurus-plugin-content-docs/current/api/effector/createEffect.md, website/client/yarn.lock, yarn.lock
Docs  => createEffect.md has been translated in Russian.
=> Docs => Translated createEffect.md to Russian

packages/effector-react/index.d.ts, packages/effector-react/ssr.d.ts, src/types/__tests__/effector-react/effectorReact.test.tsx
Hello! My team-mate found `useEvent` types issue and I wanna to fix it. I am not so good at types writing, so please review my PR and give me feedback.
Fix #500
=> Fix useEvent typings for void payload

website/client/src/pages/index.js
=> Missing import on the index page

packages/effector/index.d.ts, src/types/__tests__/effector/sample/sample.test.ts
Merge after https://github.com/effector/effector/pull/591 to avoid conflicts (PR target will automatically change to `master`)
=> Fix sample generic edge case

docs/recipes/react/todo-creator.md
When I tried to apply this example in life, typescript pointed out several typing errors, so this PR will fix them. Also, I make updates for example. I know that I should have created an issue first, but I thought that there are a small number of changes and if these edits are not accepted, I won't be particularly upset, but I remain positive :)
Thanks for the great project.
=> Fix Recipes -> React -> TODO creator

src/vue/index.ts
=> changed: deprecate $watchAsStore and $store

website/client/i18n/ru/docusaurus-plugin-content-docs/current/api/effector/sample.md
=> add sample with filter:ru

packages/effector/index.d.ts
=> Add miss typings for createWatch

docs/typescript/utility-types.md, website/client/i18n/ru/docusaurus-plugin-content-docs/current/typescript/utility-types.md, website/client/sidebars.js
Related to #634
If something else is needed, leave the comment
=> add utility types (fix #634)

docs/recipes/react/gate.md
Fix demo: wrong initial state (null, expected object) in $todo
=> Fix example of Gate usage in documentation

docs/api/effector/attach.md, docs/api/effector/is.md, packages/effector/index.d.ts, src/effector/__tests__/is.test.ts, src/effector/validate.ts, website/client/i18n/ru/docusaurus-plugin-content-docs/current/api/effector/attach.md, website/client/i18n/ru/docusaurus-plugin-content-docs/current/api/effector/is.md
I propose to release it in `22.4.0`
=> Add `is.attached` unit validator

docs/api/effector/combine.md
=> fix result from $withFn in combine docs

docs/introduction/installation.mdx
=> Fix markdown in installation guide

docs/api/effector-react/index.md, docs/api/effector-react/useUnit.md, website/client/i18n/ru/docusaurus-plugin-content-docs/current/api/effector-react/index.md, website/client/i18n/ru/docusaurus-plugin-content-docs/current/api/effector-react/useUnit.md, website/client/sidebars.js
Docs for `useUnit` basic usage
=> docs: useUnit basic usage

packages/effector-react/README.md
=> Upgrade `effector-react` readme to `useUnit`

website/client/i18n/ru/docusaurus-theme-classic/footer.json
=> Update year in footer

packages/effector-react/index.d.ts, packages/effector-react/scope.d.ts, packages/effector-solid/index.d.ts, src/types/__tests__/effector-react/effectorReact.test.tsx
=> fix: typings for useUnit in effector-{solid,react}

docs/api/effector/forward.md
=> Add recommendation to use `sample` instead of `forward`

docs/api/effector/forward.md, docs/api/effector/guard.md
=> Put warning to move away from `guard` to `sample`

docs/introduction/motivation.md, website/client/sidebars.js
- prerequisites — what is the reason to use effector
- problems it solves
- benefits
- trade-offs
- why do we want you to use it
The last two points will be covered in the next PRs
Relates #753
=> Add motivation page

packages/effector-solid/index.d.ts, src/solid/__tests__/useUnit.test.tsx, src/solid/lib/get-scope.ts, src/solid/nossr.ts, src/solid/scope.ts
=> Add forceScope opts to useUnit in solidjs

README.md
Closes https://github.com/effector/effector/issues/798
=> Adds installation guide by multiple npm package managers

packages/effector/index.d.ts, src/types/__tests__/effector/fork.test.ts
Closes: https://github.com/effector/effector/issues/813
=> Allow effects with custom error type in fork handlers

beta/docs/introduction/ecosystem.md
=> Actualize ecosystem page in the beta docs

docs/ecosystem-development/unit-shape-protocol.md, packages/effector-react/index.d.ts, packages/effector-solid/index.d.ts, src/react/__tests__/base/shapeProtocol.test.tsx, src/react/apiBase.ts, src/solid/__tests__/shapeProtocol.test.tsx, src/solid/lib/base.ts, website/client/sidebars.js
=> `@@unitShape` protocol

CHANGELOG.md, beta/docs/api/effector/allSettled.md, docs/api/effector/allSettled.md, packages/effector/index.d.ts, src/types/__tests__/effector/fork.test.ts
=> Add docs and types for allSettled(scope)

beta/docs/introduction/ecosystem.md
I assume we're going to hide package on stage 0-1 under the cut in the near future
=> [beta] Add markers of stability for ecosystem packages

src/react/apiBase.ts
=> Fix useUnit bug in nextjs

packages/effector/inspect.d.ts, src/effector/__tests__/inspect.test.ts, src/effector/inspect.ts, src/effector/region.ts
=> Fix inspect api types

src/react/__tests__/base/createGate.test.tsx, src/react/createGate.ts
=> Fix Gate component 

beta/docs/recipes/nextjs/scope-bind.md
Fixes #882
Fix type on /recipes/nextjs/scope-bind page
=> Fix targt to target

src/effector/__tests__/fork/fork.test.ts, src/effector/__tests__/fork/index.test.ts, src/effector/__tests__/fork/serialize.test.ts, src/effector/fork/fork.ts, src/effector/fork/serialize.ts, src/effector/fork/util.ts, src/effector/kernel.ts, src/effector/unit.h.ts
=> Fix sidless edge case

src/react/__tests__/base/useUnit.test.tsx, src/react/apiBase.ts
=> Fix useUnit bug on event change

packages/effector/index.d.ts, src/types/__tests__/effector/combine.test.ts
Some degradation of typings was introduced in https://github.com/effector/effector/pull/884/files
=> Fix type degradation from 22.8.2 

beta/src/content/docs/en/api/effector-react/Provider.md, beta/src/content/docs/en/api/effector-react/index.md, beta/src/content/docs/en/api/effector-react/useUnit.md, beta/src/content/docs/ru/api/effector-react/useEvent.md, beta/src/content/docs/ru/api/effector-react/useUnit.md, beta/src/navigation.ts
=> Add <Provider /> docs

beta/src/content/docs/en/api/effector-react/useEvent.md
=> Fix useEvent docs

beta/src/content/docs/en/api/effector/index.md, beta/src/content/docs/en/api/effector/module/inspect.md, beta/src/navigation.ts
=> EFX-168 Doc about module effector/inspect

beta/src/content/docs/en/api/effector/fork.md, beta/src/content/docs/en/api/effector/serialize.md, beta/src/content/docs/en/guides/server-side-rendering.md, beta/src/navigation.ts
Added `guides/server-side-rendering` guide
=> [EFX-203]: common ssr guide

beta/src/content/docs/en/api/effector/Store.md
=> [EFX-175] Remove `.thru` from the Store docs

beta/src/content/docs/en/introduction/examples.md
=> Added new example

beta/src/consts.ts, beta/src/content/config.ts, beta/src/languages.ts, beta/src/navigation.ts, beta/src/pages/uz.astro
=> Feat: begun translatin to uzbek lang

website/client/docusaurus.config.js, website/client/i18n/uz/code.json, website/client/i18n/uz/docusaurus-plugin-content-docs/current.json, website/client/i18n/uz/docusaurus-theme-classic/footer.json, website/client/i18n/uz/docusaurus-theme-classic/navbar.json, website/client/src/pages/index.js
=> Feat/(new locale) creating uz lang

beta/src/components/Landing/Companies.astro, beta/src/languages.ts, beta/src/pages/index.astro, beta/src/pages/ru.astro, beta/src/pages/uz.astro
=> EFX-142: add Companies section on Landing page

website/client/src/pages/styles.module.css
A little fix in companies section layout on mobile devices
=> Fix layout on mobile devices

beta/src/content/docs/en/api/effector/scopeBind.md, package-lock.json
=> add options for scopeBind in docs

src/effector/__tests__/fork/scopeBind.test.ts, src/effector/fork/scopeBind.ts
=> Update scopeBind fail message

beta/src/content/docs/en/api/effector/Store.md, beta/src/content/docs/en/api/effector/combine.md, beta/src/content/docs/en/api/effector/createStore.md, packages/effector/index.d.ts, src/effector/__tests__/is.test.ts, src/effector/__tests__/store/index.test.ts, src/effector/combine.ts, src/effector/createUnit.ts, src/effector/index.h.ts, src/types/__tests__/effector/combine.test.ts, src/types/__tests__/effector/guard.test.ts, src/types/__tests__/effector/index.test.ts, src/types/__tests__/forest/index.test.ts
=> Void skip deprecation

packages/effector/index.d.ts, src/types/__tests__/effector/scopeBind.test.ts
=> Add third generic type for effect in scopeBind

src/babel/__tests__/__snapshots__/babel-plugin.test.js.snap, src/babel/__tests__/fixtures/default-factories.js, src/babel/babel-plugin.js
=> Add custom `patronum` handling

beta/src/consts.ts, beta/src/languages.ts, beta/src/pages/uz.astro
=> improved uzb translation

src/vue/__tests__/EffectorScopePlugin.test.ts, src/vue/__tests__/useUnit.test.ts, src/vue/lib/get-scope.ts, src/vue/useUnit.ts
- Add test for `EffectorScopePlugin` from `effector-vue`
- Fix scopefull store reading in `useUnit` from `effector-vue/composition`
=> Tests for EffectorScopePlugin

src/effector/restore.ts
=> Remove `restore($store)` support

beta/src/content/docs/en/guides/migration.md, beta/src/navigation.ts
=> Add migration guide

src/react/apiBase.ts
=> Use `useUnit` in `useList` implementation

packages/effector/index.d.ts, src/types/__tests__/effector/guard.test.ts, src/types/__tests__/effector/index.test.ts, src/types/__tests__/forest/index.test.ts
Second argument is not available anymore, it should be removed from typings
=> Fix store map typings

documentation/astro.config.ts, documentation/package.json, documentation/pnpm-lock.yaml, documentation/src/styles/index.css
=> EFX-125 Add hash-link for headings

documentation/src/content/docs/ru/api/effector-react/useProvidedScope.md
Added Russian translation for the `useProvidedScope` hook.
=> Added docs for useProvidedScope.md

src/effector/__tests__/combine.test.ts, src/effector/combine.ts
=> Fix combine forbidden keys

documentation/src/content/docs/en/introduction/ecosystem.md
=> docs: add effector-reform into ecosystem list

packages/effector/index.d.ts, src/types/__tests__/effector/attach.test.ts, src/types/__tests__/effector/effect.test.ts
=> Fix types for createEffect and attach in factories with generics

src/vue/__tests__/useUnit.test.ts
=> Fix typo in Vue useUnit test

packages/effector-vue/README.md
=> docs(README): add README.md to effector-vue

documentation/src/content/docs/ru/introduction/ecosystem.md
updated description for Russian documentation
=> Update ecosystem.md [ru]

documentation/src/content/docs/en/introduction/ecosystem.md
=> Update url of effector-reform repo

documentation/src/content/docs/en/introduction/ecosystem.md, documentation/src/navigation.ts
=> Docs fix withease links

documentation/src/content/docs/ru/introduction/community.md
- Translate the community page into Russian;
- Please check the names and facts are correct;
=> [Translate] Community RU

documentation/src/content/docs/en/introduction/community.md, documentation/src/content/docs/en/introduction/ecosystem.md, documentation/src/content/docs/en/introduction/examples.md, documentation/src/content/docs/en/introduction/motivation.md, documentation/src/content/docs/ru/introduction/community.md, documentation/src/content/docs/ru/introduction/ecosystem.md, documentation/src/content/docs/ru/introduction/motivation.md
=> updated docs examples

documentation/src/content/docs/en/introduction/examples.md
Created new example for using Effector and React with tree-like structures.
=> Add new example in "More examples"

documentation/pnpm-lock.yaml, documentation/src/components/LeftSidebar/LeftSidebar.astro, documentation/src/components/PageContent/PageContent.astro, documentation/src/components/PageNavigation.astro, documentation/src/components/Show.astro, documentation/src/consts.ts, documentation/src/icons/ArrowLeft.astro, documentation/src/icons/ArrowRight.astro, documentation/src/icons/ChevronRight.astro, documentation/src/navigation.ts
=> Implement navigation for sections/topics are now collapsible

documentation/src/components/PageContent/PageContent.astro
=> style: breadcrumbs for navigation

documentation/src/content/docs/en/api/effector/Effect.md, documentation/src/content/docs/en/api/effector/Event.md, documentation/src/content/docs/en/api/effector/Store.md
=> Fix unit API documentation types

documentation/src/navigation.ts
- Adds translation to navigation for sections that already have translation;
=> [Translate RU] Update navigation

documentation/package.json, documentation/pnpm-lock.yaml, documentation/src/components/Tabs/TabItem.astro, documentation/src/components/Tabs/Tabs.astro, documentation/src/components/Tabs/get-id.ts, documentation/src/components/Tabs/init-tabs.ts, documentation/src/content/docs/en/introduction/installation.mdx, pnpm-lock.yaml
This PR adds a new component Tabs with keyboard control and accessability
=> feat(documentation): add tabs component

documentation/src/content/docs/en/essentials/reactivity.md, documentation/src/content/docs/ru/essentials/reactivity.md, documentation/src/navigation.ts
=> Add page about reactivity in effector

documentation/src/components/LeftSidebar/LeftSidebar.astro, documentation/src/content/docs/en/introduction/core-concepts.md, documentation/src/content/docs/ru/introduction/core-concepts.md, documentation/src/navigation.ts, documentation/src/styles/theme.css
add new Core concepts page
small style changes
before
after
=> Docs new core concepts page

documentation/src/components/Header/ThemeSwitch.astro
=> fix(docs): fix auto switch theme

documentation/src/content/docs/en/api/effector-react/useStoreMap.md
=> docs: add warning about undefined values returned from useStoreMap selector function

documentation/src/content/docs/en/essentials/testing.mdx, documentation/src/content/docs/ru/essentials/testing.mdx
=> feat(docs): add info about testing event

documentation/src/content/docs/en/essentials/manage-states.mdx, documentation/src/content/docs/ru/essentials/manage-states.mdx
=> feat(docs): add info about skipVoid in manage-states

documentation/src/components/Tabs/Tabs.astro, documentation/src/content/docs/en/introduction/get-started.mdx, documentation/src/content/docs/ru/introduction/get-started.mdx, documentation/src/navigation.ts
=> Docs get started page

documentation/src/navigation.ts
=> hotfix(docs): fix link fpr computation-priority

documentation/src/components/LeftSidebar/LeftSidebar.astro, documentation/src/components/LeftSidebar/SidebarScrollRestore.astro
=> Add scroll restore

documentation/src/components/RightSidebar/RightSidebar.astro
=> Toc render on server

documentation/src/components/Header/Search.astro
=> Docs: close search dialog when user clicks outside

documentation/src/content/docs/en/essentials/unit-composition.md, documentation/src/content/docs/ru/essentials/unit-composition.md
=> docs: fix return value in function 

documentation/src/content/docs/en/api/effector/Store.md, documentation/src/content/docs/ru/api/effector/Store.md
=> docs: rewrite Store API documentation

documentation/src/content/docs/en/api/effector/sample.md, documentation/src/content/docs/ru/api/effector/sample.md, documentation/src/sidebar-config.ts
Changes:
- update sample API page
- move attach and merge to methods sidebar instead of creators
- add ru translation for some sidebar items
=> docs sample api update

documentation/src/content/docs/en/api/effector/Store.md, documentation/src/content/docs/en/api/effector/createEvent.md, documentation/src/content/docs/en/api/effector/createStore.md, documentation/src/content/docs/en/guides/troubleshooting.mdx, documentation/src/content/docs/ru/api/effector/createEvent.md, documentation/src/content/docs/ru/api/effector/createStore.md, documentation/src/content/docs/ru/guides/troubleshooting.mdx
=> DOCS: update createEvent/createStore pages

documentation/src/content/docs/en/api/effector/Effect.md, documentation/src/content/docs/ru/api/effector/Effect.md
=> docs(effect api): fix effect api page

documentation/src/content/docs/en/api/effector/createEvent.md, documentation/src/content/docs/ru/api/effector/createEvent.md
=> docs: add common errors section to createEvent page

documentation/src/content/docs/ru/introduction/get-started.mdx, package.json
- Fix typo in Russian translate
- Corepack automatically setting
=> Docs: fix typo in get started chapter [RU]
