src/effector/sample.js

`let current = undefined`
minifies to
`let e=void 0`
when
`let current`
minifies to just
`let e`
It will save some bytes :)

Remove `undefined` in sampleStore/sampleEvent

---

src/effector/__tests__/sample.test.js
src/effector/sample.js

Add tests:
- store has the same state as source
- store has its own defaultState
- store updates if source updates
- store updates only if source is changed
Fix:
- Remove watch and use getState
Let's discuss sampleStore intended behaviour

Fix sampleStore, remove unnecessary watcher

---

packages/effector/index.d.ts

Closes #102 
Note: `Exclude<E, undefined>` needed to remove noise from typings: `string | undefined | void` is the same as `string | void`

Nicer typings for createApi()

---

website/editor/src/dynamic.js

---
<details>
<summary>
</summary>
- [#149: restore function doesn't work in REPL](https://issuehunt.io/repos/123197392/issues/149)
---
</details>

#149 Fix crash in try environment while use restore

---

packages/effector/index.d.ts

fixes #155
Probably should be a breaking change, because sample now accepts types of source and clock instead of their values

Update TypeScript sample typings

---

packages/effector/index.d.ts
packages/effector/index.js.flow
src/types/__tests__/__snapshots__/run-tests.test.js.snap
src/types/__tests__/run-tests.test.js
src/types/types.test.js

Fixes https://github.com/zerobias/effector/issues/165
---
<details>
<summary>
</summary>
- [#165: Property "shortName" is missing on types for Event and Effect](https://issuehunt.io/repos/123197392/issues/165)
---
</details>

Add shortName to types

---

packages/effector/index.d.ts

Refine type of payload if filter got a predicate function as a callback
```javascript
import { createEvent } from 'effector'
const event = createEvent<string | number>()
const isString = (value: any): value is string => typeof value === 'string'
const isNumber = (value: any): value is number => typeof value === 'number'
const str = event.filter({fn: isString}) // Event<string>
const num = event.filter({fn: isNumber}) // Event<number>
str.watch(value => value.slice()) // OK now
num.watch(value => value.toFixed(2)) // OK now
```

Update type of Event.filter

---

docs/api/effector/createEffect.md

Since *Effect* has *Events* and *Stores* within it, people may assume they can *Forward* them, as they would regular *Events* and *Stores*. However, this behavior is not implied, and hence not supported.

Add impossibilty of forwarding parts of *Effect*

---

packages/effector/index.d.ts

Fixes #106
---
<details>
<summary>
</summary>
- [#106: createEffect doesn't resolve void Params](https://issuehunt.io/repos/123197392/issues/106)
---
</details>

Fix createEffect TypeScript type with void parameter

---

.gitpod.yml

Hello! 👋
I noticed that your `.gitpod.yml` specifies two terminals:
```yaml
tasks:
- init: yarn
- command: yarn test:watch
```
I think that was unintentional, and that `init` and `command` should run in the same Terminal, one after the other:
```yaml
tasks:
- init: yarn
command: yarn test:watch
```
(one `-` === one Terminal)

fix .gitpod.yml: run `init` and `command` in the same terminal

---

website/editor/src/styles.css

fixes #180
Just a tiny css tweak on the mobile media query so you can use the editor whilst you have an error being displayed;
---
<details>
<summary>
</summary>
- [#180: Error overlay is on top of navigation UI on mobile](https://issuehunt.io/repos/123197392/issues/180)
---
</details>

#180 fix mobile error overlay

---

packages/effector/index.d.ts

Add overload to handle cases with non-intersecting types
```javascript
const a = createEvent<number>()
const b = createEvent<string>()
const merged = merge([a,b])
```
**Current behaviour**: Error
```
Type 'Unit<string>' is not assignable to type 'Unit<number>'.
Type 'string' is not assignable to type 'number'.
```
**After fix**: No error. `typeof merged = Event<string | number>`

improve typescript inference for merge method

---

packages/effector/index.d.ts
src/types/__tests__/effector/effect.test.js

The problem with current createEffect typescript typings is that [`FN extends () => infer Done`](https://github.com/zerobias/effector/blob/master/packages/effector/index.d.ts#L300) condition satisfies zero-or-one-arity effect handlers. Handler like `(x?: TYPE) => any` will produce `Effect<void,...>`. New test suite with updated snapshots [displays](https://github.com/zerobias/effector/commit/eef87cefab3068f73cc3ff2d2205484631d3bd47#diff-0015a2dd8aaa7b887423704ae136efeeR245) these errors.
You may see new typings proposal partially improving current situation. I added some comments to explain why it was difficult to deal with type `any`.
The last commit contains finally updated snapshots to demonstrate how proposed typings work.

Ts infer optional params from effect handler

---

packages/effector/index.d.ts

```typescript
const source = createEvent<string | number | null | {}>()
const events = split(source, {
numbers: (a): a is number => typeof a === 'number',
strings: (a): a is string => typeof a === 'string',
not_refined: (a) => !!a,
})
// Event<number>, no error
events.numbers.map(a => a.toFixed())
// Event<string>, no error
events.strings.map(a => a.charCodeAt(0))
// still fails, object is possibly null
events.not_refined.map(a => a.toString())
```

Allow predicate refinements for split

---

CHANGELOG.md

Mention `name` property of `sample` parameters list right below the `guard` feature introduction.

introduce `name` property in sample parameters list

---

packages/effector/index.d.ts
src/types/__tests__/effector/forward.test.js

Fixed wrong `forward` typings behavior, when forwarding FROM "less strict" type TO "more strict" type throws no errors.

Better `forward` typings (TS)

---

packages/effector/index.d.ts
src/types/__tests__/effector/combine.test.js

Hello!
Effector 20.5.0:
```
import { combine, Store } from 'effector';
const sn = {} as Store<number>;
const ss = {} as Store<string>;
const dict = combine({ sn, ss }); // Store<{ sn: number; ss: string; }>
//                                   ^^^^^^^^^^^ That's ok! ^^^^^^^^^^^
const tuple = combine([sn, ss]); // Store<(Store<number> | Store<string>)[]>
//                                  ^^^^^^^^^^^ Looks incorrect ^^^^^^^^^^^
```
After typings fix:
```
const tuple = combine([sn, ss]); // Store<[number, string]>
//                                  ^^^^ Now that's ok too!
// As a consequence this will work after accepting the proposal
combine([sn, ss], ([n, s]) => {
n.toExponential; // OK, has type specific method
s.charAt; // OK, has type specific method
});
```

[TS] typings fix for `combine`, accepting list of stores

---

src/types/__tests__/effector/restore.test.js

Hello! It seems like there is no test suite for `restore` typings. I've created one. Could you please review?
If you accept this, I'll start working on #239 . The second `describe` section in the file has corresponding failing tests. The thitd `describe` section has tests which are nessesary to make sure that future fix won't break basic `restore` behavior.

Create typings test suite for `restore`

---

packages/effector/index.d.ts
src/types/__tests__/effector/sample.test.js

+ test suit for `sample` cases using `target` forwarding
+ add NoInfer type hint to `sample` overloads using `target`
This will fix #247

Sample target forwarding typings

---

packages/effector/index.d.ts
src/types/__tests__/effector/sample.test.js

Add support for the following callable `sample` signatures with combinable source:
+ sample(storeObj, clock)
+ sample(storeList, clock)
+ sample(storeObj, clock, fn)
+ sample(storeList, clock, fn)
+ sample({ source: storeObj, clock })
+ sample({ source: storeList, clock })
+ sample({ source: storeObj, clock, target })
+ sample({ source: storeList, clock, target })
+ sample({ source: storeObj, clock, fn })
+ sample({ source: storeList, clock, fn })
+ sample({ source: storeObj, clock, fn, target })
+ sample({ source: storeList, clock, fn, target })

[TS] Add typings support for sample accepting combinable source argument

---

packages/effector-react/index.d.ts
src/types/__tests__/effector-react/useStoreMap.test.tsx

This uses tuple hack we already used for `combine` to improve inference for array of keys

Improve useStoreMap typings

---

packages/effector/index.d.ts
src/types/__tests__/effector/sample.test.js

Workaround for https://github.com/microsoft/TypeScript/issues/35162 (tharks to @artalar for help)
Now we can directly assign `guard` invocation to `sample`'s `clock` argument without losing inference in `sample`'s `fn`
```ts
import {sample, guard, createStore, createEvent} from 'effector'
const source = createStore(100)
const clock = createEvent<number>()
sample({
source,
clock: guard(clock, {
filter: clock => clock > 0,
}),
fn: (source, clock) => source + clock, // clock is of type `number` now (previously inferred as `unknown`)
})
```

[Typings] Workaround for typescript issue 35162

---

website/editor/src/index.html

On website for docs, api was edited links. On REPL not. Now fixed

fix links in repl

---

packages/effector-dom/index.d.ts
src/dom/__tests__/index.test.ts
src/dom/render/list.ts

Some else way to render items from `list` function. effector like the way (sample, guard)
```js
const $users = createStore([
{name: 'Alice', id: 1},
{name: 'Bob', id: 2}
])
list({
source: $users,
key: 'id',
fn: ({store}) => {
h('span', {
text: store.map(({name}) => name)
})
}
})
```

created option [fn] like cb

---

docs/api/effector/Store.md
packages/effector/index.d.ts
packages/effector/index.js.flow
src/effector/__tests__/store/on.test.js
src/effector/createUnit.js
src/types/__tests__/effector/store.test.js

```js
import {createEvent, createStore} from 'effector'
const store = createStore(0)
const changedA = createEvent()
const changedB = createEvent()
store.on([changedA, changedB], (state, params) => state + params)
store.watch(value => {
console.log('updated', value)
})
changedA(2)
// => updated 2
changedB(2)
// => updated 4
store.off(changedB)
```

Add support for trigger[] in store.on

---

docs/api/effector/sample.md

If the `clock` is not passed, sample will be trigged on every `source` update (instead of `target`)

Fix in sample api

---

website/editor/src/features/logs/lib/console/react-inspector/fork/object-inspector/ObjectPreview.tsx

**Current behavior**: `Error` objects are rendered in REPL as empty `{}` object.
**Reproduction**: https://share.effector.dev/T0okfYak

console.log in REPL does not render Error objects in a right way

---

website/client/src/pages/index.js

Those images don't need to have an alt tag, because they are decorative images. And by the way, it's also wrong to set an alt with text which is already on the screen cuz screen reader users will hear this text twice and that makes no sense.

small accessability fix for the website

---

website/client/docusaurus.config.js

I wanted to fix a bug in the documentation and pressed "edit this page" and I was thrown somewhere wrong.\
After a little research, I realized that the bug was that docusaurus did not take into account the case, that the documentation could be higher than the file system level. The library connects[ `path` and `editUrl` ](https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-utils/src/index.ts#L350-L357) into one to get the final url (I don't know why). 
This causes the final url to lose 2 folders in the path and break the destination link.
This cannot be fixed quickly, but I have noticed that browsers handle relative url in links correctly, and it occurred to me to add subdirs in editUrl to get the correct final link.
wrong: 
correct:

fix: broken relative path in docs

---

packages/effector/index.d.ts

```js
const fx = createEffect().use(() => null)
const d = fx.filter({
fn(a) {
return a > 0
},
})
d.watch(console.log)
fx(5)
fx(0)
fx(1)
```
https://share.effector.dev/G34PZ7qF

add filter and filterMap types to Effect

---

packages/effector/index.d.ts
packages/effector/index.js.flow
src/effector/__tests__/attach.test.ts
src/effector/attach.ts
src/types/__tests__/effector/attach.test.js
src/types/__tests__/effector/sample/targetForwarding.test.js

```ts
const originalFx = createEffect(() => {
// your logic
})
const derivedFx = attach({ effect: originalFx })
```
inspired by: https://github.com/effector/patronum/issues/79

add support for attach without mapParams and source simultaneously

---

packages/effector/index.d.ts
src/types/__tests__/effector/effect.test.js
src/types/__tests__/effector/event.test.js

Use case:
```ts
type voidFn = () => void
const fn = (callback: voidFn) => {
if(callback) callback()
}
const voidEvent: Event<void> = createEvent();
fn(voidEvent); // TS2345: Argument of type 'Event ' is not assignable to parameter of type 'voidFn'.
```
This PR adds void function interop:
```ts
const voidFn: () => void = createEvent<void>()
const voidFn1: () => void = createEvent<undefined>()
const voidFn2: () => void = createEvent<any>()
const event1 = createEvent<undefined>()
event1()
const event2 = createEvent<any>()
event2()
```
The only weak spot is the text of the message:
```ts
const event1 = createEvent<number>()
event1() /* Error
The 'this' context of type 'void' is not assignable to method's 'this' of type '"Error:
Expected 1 argument, but got 0"'.
*/
```
All tests pass!

[TS] Void function interop

---

packages/effector/index.d.ts
src/types/__tests__/effector/event.test.js

`prepend` method infers payload type from the function argument if it exists... and if there is no argument the resulting payload type will be of type `unknown`. This is a bug because a user cannot call `Event<unknown>` without params -  it waits for 1 argument with type `unknown`.
```ts
const event = createEvent<string>();
const prepended = event.prepend(() => 'foo') // Event<unknown>
prepended() // TS error: Expected 1 arguments, but got 0.
```
To bypass the type error, a user needs to specify `void` manually: 
```ts
const event = createEvent<string>();
const prepended = event.prepend<void>(() => 'foo') // Event<void>
prepended() // ok
```
But we can fix this by adding a default type to prepend's `Before`:
```ts
prepend<Before = void>(fn: (_: Before) => Payload): Event<Before>
```
As …

Add type tests for prepend, improve prepend type

---

packages/forest/index.d.ts
src/types/__tests__/forest/index.test.ts

```tsx
const $data = createStore({
foo: 1,
bar: "two",
baz: true,
})
const d: [
Store<number>,
Store<boolean>,
Store<string>,
] = remap($data, ['foo', 'baz', 'bar'])
```

allow to use `remap` without `as const`

---

docs/api/effector-react/useEvent.md
packages/effector-react/index.d.ts
packages/effector-react/ssr.d.ts
src/react/__tests__/scopes.test.tsx
src/react/ssr.ts
src/types/__tests__/effector-react/effectorReact.test.js

```tsx
import React from "react";
import { useEvent } from "effector-react/ssr";
import { emailChanged, passwordChanged } from "./model";
export function ExampleComponent() {
const handlers = useEvent({ emailChanged, passwordChanged });
return (
<div>
<input onChange={handlers.emailChanged} />
<input onChange={handlers.passwordChanged} />
</div>
);
}
```
---
```tsx
import React from "react";
import { useEvent } from "effector-react/ssr";
import { emailChanged, passwordChanged } from "./model";
export function ExampleComponent() {
const [email, password] = useEvent([emailChanged, passwordChanged]);
return (
<div>
<input onChange={email} />
<input onChange={password} />
</div>
);
}
```

add support of object/array of events for `useEvent`

---

docs/glossary.md

I suppose there should be a word 'trigger' and not 'tigger' ;)

Fixed a typo in glossary.md

---

packages/effector/index.d.ts

If type of shape is passed explicitly to `combine`, it's impossible to use Stores in it, because of TS error:
This extension makes this behavior possible:

extend combine shape type

---

packages/effector/index.d.ts

Fix for #463 
Current type has leak for infinite recursion because of `T extends any` condition - it's always true. But TS still handles this type without any issues, that's why I didn't notice the leak.
New condition has safe guard from infinite recursion and it works the same.

prevent infinite recursion in `UnionToStoresUnion` type

---

.eslintrc
docs/api/effector-react/useStoreMap.md
package.json
src/react/__tests__/scopes.test.tsx
src/react/ssr.ts
yarn.lock

```js
import {Provider, useStoreMap} from 'effector-react/ssr'
const root = createDomain()
const $list = root.createStore([
{id: 1, title: 'a'},
{id: 2, title: 'b'},
])
const Link = ({id}) => {
const item = useStoreMap({
store: $list,
keys: [id],
fn: (list, [id]) => list.find(item => item.id === id),
})
return <div key={item.id}>{item.title}</div>
}
const scope = fork(root)
ReactDOM.render(
<Provider value={scope}>
<Link id={1} />
</Provider>,
document.getElementById('root')
)
```
```
t is undefined
exports.useStoreMap
ssr.js:1:4457
```
[Repl](https://share.effector.dev/tsUYIirX)
<details>
<summary>Report from user of effector-react v21.3.0</summary>
</details>

fix useStoreMap in scope

---

website/client/src/pages/styles.module.css

Removed horizontal scrolling from the main page of the site from the "Features" block (Chrome 89, Firefox). There is probably a better way to solve the problem.

Fix docs index page horizontal scroll

---

docs/api/effector-react/createComponent.md

Line 46 should read `// any stuff here` instead of `// any staff here`

fix typo for `staff` on line 46

---

docs/api/effector/attach.md

grammatically and semantically correct naming for this store would be `requestsSent` since it counts how many requests have been sent so far.

change requestsSend to requestsSent

---

packages/effector-react/package.json

**Describe the bug**
React native's metro bundler ignores `effector-react` and shows a warning.
Similar issues have been reported in many other projects as listed in [this react native cli issue](https://github.com/react-native-community/cli/issues/1168#issue-617427926) and [the fix used by those projects is quite simple and seemingly low risk](https://github.com/i18next/i18next-http-backend/commit/1d8da7909425eb33ab286cd73ee53bb48a1a3dc4#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R8).
**To Reproduce**
Steps to reproduce the behavior:
With node 16.13.0 and yarn 1.22.17 installed (as of this writing, the latest available in homebrew)...
1. Create a new react native app with `npx react-native init DummyProj`
2. `cd DummyProj/`
3. Install effector-react with `yarn add effector-react`
4. Start the …

Fix exports for react-native

---

packages/effector/index.d.ts
src/types/__tests__/effector/generated/sampleArrayTarget.test.ts
src/types/__tests__/effector/sampleFilter/sampleFilterArrayTarget.test.ts
src/types/__tests__/effector/sampleFilter/sampleFilterWideNarrow.test.ts

The wide tuple check is built into the `IfAssignable` helper:
```ts
: T extends Array<any>
? number extends T['length']
? N
: U extends Array<any>
? number extends U['length']
? N
: TupleObject<T> extends TupleObject<U> ? Y : N
: N
: N
```

Fix wide tuple (sample types)

---

packages/effector/index.d.ts
src/types/__tests__/effector/sample/clockArray.test.ts

It's interesting that it became possible at all with this approach. We could use this feature for `prepend` (but we don't need it for sample)

Do not infer type from returned unit for sample

---

src/effector/__tests__/fork/allSettled.test.ts
src/effector/fork/allSettled.ts
src/effector/fork/createScope.ts

Fixes #608 (by fixing serialize issue)
Changelog:
- added tests for `allSettled($store, ...)` cases
- added fix for the case
Apparently, the `getParent(storeStack)` line in `storeChange` node defintion is needed to check, if store is created from combine or map, but the same check also led to `$store` as starting unit for `allSettled` being skipped in serialization - because there is no "parent trigger" 🤔

Support store as `allSettled` argument

---

packages/effector/index.d.ts
src/types/__tests__/effector/split.test.ts

I'm not sure but we probably need to check that  `UnitValue<Match> extends CaseTypeReader<Cases, keyof Cases>` in the first SplitType fork.
I doubt it because I see the failed tests. Maybe that's how it was supposed to be

added: edge case for split

---

docs/api/effector/split.md

Fix typo in `split` documentation

Fix typo in documentation

---

docs/api/effector/attach.md
website/client/i18n/ru/docusaurus-plugin-content-docs/current/api/effector/attach.md

[documentation] `attach` operator has an overload with plain function as `effect` option. Clarify relation of `source` option to `effect` one in this case.

Fix attach operator with plain function case defails in documentation

---

src/forest/__tests__/classList.test.ts
src/forest/index.h.ts
src/forest/method/h.ts
src/forest/method/spec.ts
src/react/__tests__/createGate.test.tsx

Previously if I need to switch many classes via single condition I need to list them all:
```ts
const $isEnabled = createStore(true)
const $isDisabled = $isEnabled.map(is => !is)
spec({
classList: {
'bg-black': $isEnabled,
'text-white': $isEnabled,
'bg-white': $isDisabled,
'text-black': $isDisabled,
},
})
```
This PR allows to list many classes in the same property:
```ts
const $isEnabled = createStore(true)
const $isDisabled = $isEnabled.map(is => !is)
spec({
classList: {
'bg-black text-white': $isEnabled,
'bg-white text-black': $isDisabled,
},
})
```
It is especially useful with tools like Tailwind
---
As a benefit it supports dynamic classes:
```ts
const $classes = $isEnabled.map(is => is ? 'text-white bg-black' : 'text-black bg-white')
spec({ classList: [$classes] })
```

Allow to to set many classes in a single `classList` property

---

README.md
docs/introduction/installation.mdx
examples/cdn.html
website/client/i18n/ru/docusaurus-plugin-content-docs/current/introduction/installation.mdx

I think it'd be appropriate for effector to update its CDN documentation.
unpkg is unmaintained and [full of issues](https://github.com/mjackson/unpkg/issues). I switched the documentation over to [jsDelivr](https://www.jsdelivr.com/) since it's actively maintained and is much more reliable due to its [fallback system](https://www.jsdelivr.com/network/infographic).
Let me know if there are any concerns!

docs: switch unpkg to jsdelivr

---

README.md
website/client/docusaurus.config.js
website/client/i18n/ru/code.json
website/client/i18n/ru/docusaurus-theme-classic/navbar.json
website/client/i18n/zh-cn/code.json
website/client/i18n/zh-cn/docusaurus-theme-classic/navbar.json
website/client/src/pages/index.js

Following discussion, I've renamed "REPL" term to "Playground".
Also changed button "Try it out" to "Playground", for consistency. Discussible.
For Russian and Chinese localizations I've renamed "REPL" to what is written on "Try it out" button — "Попробовать онлайн" and "在线试用" accordingly.

website: rename REPL in Playground

---

packages/effector/index.d.ts
src/effector/__tests__/fork/scopeBind.test.ts
src/effector/fork/scopeBind.ts

Closes #666
- Added a new option to `scopeBind` - `safe: boolean`

`safe` mode for `scopeBind`

---

README.md

Whenever navigate by links from packages sections, page not found appears

Fix packages links in the readme

---

packages/effector-react/index.d.ts
packages/effector-react/index.ts
packages/effector-react/scope.ts
src/react/__tests__/base/useUnit.test.tsx
src/react/nossr.ts
src/react/scope.ts
src/react/ssr.ts

Add forceScope parameter to useUnit in react

---

src/react/__tests__/base/scopes.test.tsx
src/react/ssr.ts

Recent PR introduced a breaking change - `effector-react/scope` lost its warnings against usage without `Provider`
This PR reintroduces this behavior and adds some tests for that.

Fix react scope behavior

---

packages/effector-react/index.d.ts
packages/effector-react/scope.d.ts
src/react/__tests__/base/useEvent.test.tsx
src/react/__tests__/base/useList.test.tsx
src/react/__tests__/base/useStore.test.tsx
src/react/apiBase.ts
src/react/nossr.ts
src/react/ssr.ts
src/types/__tests__/effector-react/effectorReact.test.tsx
src/types/__tests__/effector-react/useStoreMap.test.tsx

Finalize changes in `effector-react` that was started in https://github.com/effector/effector/pull/776 and https://github.com/effector/effector/pull/785.
Since `effector-react` and `effector-react/scope` are both fully bundled, it is impossible to mix it in one project (because of different instances of React context), so we had to provide a way to use only `effector-react` for scope-full runtime.
Public changes:
1. Make `useStore` isomorphic
2. Make `useStoreMap` isomorphic
3. Make `useList` isomorphic
4. Make `useEvent` isomorphic
Internal changes:
Rewrite type tests of `useEvent` (now it is not call `useEvent`) because it is no React in test bundle for type-tests. @AlexandrHoroshih previously made the same for `useUnit` tests.

Isomorphic React, part 3

---

packages/effector/index.d.ts
src/effector/createUnit.ts
src/effector/unit.h.ts
src/types/__tests__/effector/store.test.ts

`$store.reinit` - event to set default value into store
```typescript
const $store = createStore<Array<number>>([]);
sample({
clock: someEffectFailed,
target: $store.reinit
});
// subscribe on store reinit
sample({
clock: $store.reinit,
fn: () => console.log("store value set to default")
});
```

event<void> $store.reinit added

---

src/effector/__tests__/combine.test.ts
src/effector/combine.ts

Effector uses Array.slice internally to prepare argument object for a user, there is a case, where it was broken
Changelog:
- Added tests against breaking `combine` argument in userland via `.slice = undefined` or similiar code
- Changed `arr.slice()` to `[...arr]`

Protect against combine argument being broken via Array.slice

---

src/effector/__tests__/derived.test.ts
src/effector/createUnit.ts

Made common function to pass methodName for reset and on separately

Separate warning message for reset derived store

---

packages/effector/index.d.ts
src/types/__tests__/effector/restore.test.ts

Calling `restore` with Event or Effect without second `defaultState` argument will fail with runtime error.
But typescript will not warn about it, so you can miss this until you actually run the code.
I tried to add some type guards against it.

Forbid restore(event) and restore(effect) in types

---

src/effector/__tests__/fork/serialize.test.ts
src/effector/createUnit.ts
src/effector/fork/createScope.ts
src/effector/fork/fork.ts
src/effector/fork/serialize.ts
src/effector/unit.h.ts

`serialize: ignore` must ignore serialize event `fork({values})` is used

---

beta/src/components/RightSidebar/TableOfContents.module.css
beta/src/consts.ts
beta/src/content/docs/en/api/effector/Event.md
beta/src/content/docs/en/explanation/events.md
beta/src/content/docs/en/explanation/glossary.md
beta/src/navigation.ts
beta/src/styles/index.css
beta/src/styles/theme.css

[Rendered API/Event](https://github.com/effector/effector/blob/docs/event-rewrite/beta/src/content/docs/en/api/effector/Event.md)
[Rendered Explanation/Events](https://github.com/effector/effector/blob/docs/event-rewrite/beta/src/content/docs/en/explanation/events.md)

beta: Fully rewrite `Event` API page

---

src/effector/__tests__/fork/hydrate.test.ts

`@effector/next` library now uses custom implementation of `hydrate` under the
hood, which relies on some internals of `Scope` object
This implementation is planned to be, one way or another, merged into the core
version, but we're not quite there yet, and a bit more research should be done.
We're also are not planning on dropping Next.js support, so stability of these internals becomes a concern.
So, for now, we're only testing that the custom implementation works as
expected.

Add tests for effector-next

---

docs/api/effector/attach.md
packages/effector/index.d.ts
src/effector/__tests__/attach.test.ts
src/effector/__tests__/domain.test.ts
src/effector/attach.ts

Allow `domain` to be used in `attach` without parent effect

---

beta/src/components/Landing/Stats.astro

This MR adds links to cards, so users will be redirected to corresponding web pages on clicking a card.
The following links were chosen:
- size – https://bundlephobia.com/package/effector@latest
- contributors – https://github.com/effector/effector/graphs/contributors
- stars – https://star-history.com/#effector/effector&Date
- downloads – https://npmtrends.com/effector
- latest – https://github.com/effector/effector/releases
- license – https://raw.githubusercontent.com/effector/effector/master/LICENSE
Looking forward to hearing your opinions and suggestions 👍

EFX-205 add links for stats cards

---

beta/src/content/docs/en/api/effector-vue/EffectorScopePlugin.md
beta/src/content/docs/en/api/effector-vue/VueSSRPlugin.md
beta/src/content/docs/en/api/effector-vue/index.md
beta/src/content/docs/en/api/effector-vue/module/composition.md
beta/src/content/docs/en/api/effector-vue/module/ssr.md
beta/src/content/docs/en/api/effector-vue/useEvent.md
beta/src/navigation.ts
packages/effector-vue/index.d.ts
packages/effector-vue/ssr.d.ts
src/vue/EffectorScopePlugin.ts
src/vue/index.ts
src/vue/ssr/VueSSRPlugin.ts
src/vue/ssr/useEvent.ts

effector-vue/ssr deprecated

---

packages/effector-vue/composition.d.ts
src/vue/__tests__/useUnit.test.ts

- Add test for batching of `useUnit` from `effector-vue/composition`
- Fix typings of `useUnit` from `effector-vue/composition`
fixes #783

Batching test

---

documentation/src/content/docs/en/api/effector/Event.md
documentation/src/content/docs/en/api/effector/Store.md
documentation/src/content/docs/en/explanation/events.md

`Event extends ReadonlyEvent` was the initial idea for a split of callable and non-callable types. After that we went with `EventCallable extends Event` instead, but some of the docs are still mentioning the initial approach

Fix docs: `ReadonlyEvent` fixed

---

packages/effector-react/index.d.ts

One of useEvent overloads was not marked as deprecated, therefore ide may not mark this method as deprecated

Add deprecation to useEvent overload

---

documentation/src/layouts/Landing.astro
documentation/src/layouts/MainLayout.astro

The inconsistency in the width of the header element was causing a layout shift issue, which happens when the user transitions from the landing page to the docs pages, and vice versa.
This merge request ensures that the widths across various sections of the website are consistent and aligned.
**Docs** 
**Landing page (before)**
**Landing page (after)**

EFX-140 align header width in different parts of the website

---

documentation/src/content/docs/en/api/effector-vue/EffectorScopePlugin.md

typofix `EffectorScopePlugin.md`

---

CHANGELOG.md
documentation/src/content/docs/en/api/effector/createStore.md
documentation/src/content/docs/en/api/effector/serialize.md
documentation/src/content/docs/ru/api/effector/Scope.md
examples/react-ssr/src/server.tsx
examples/serverless-ssr/src/server/ssr.ts
packages/effector/index.d.ts
src/babel/__tests__/__snapshots__/babel-plugin.test.js.snap
src/babel/__tests__/fixtures/imports-globals.js
src/babel/__tests__/fixtures/imports.js
src/babel/__tests__/fixtures/references.js
src/effector/__tests__/fork/fork.test.ts
src/effector/__tests__/fork/index.test.ts
src/effector/__tests__/fork/serialize.test.ts
src/effector/fork/createScope.ts
src/effector/fork/fork.ts
src/effector/fork/serialize.ts
src/effector/unit.h.ts
src/forest/__tests__/ssr/index.test.ts
src/react/__tests__/base/scopes.test.tsx
src/solid/__tests__/scopes.test.tsx
src/types/__tests__/effector/fork.test.ts

- Delete deprecated `fork(domain)` overload
- Delete deprecated option `onlyChanges` in `fork` function

Delete `fork(domain)` overload

---

CHANGELOG.md
babel.config.js

fixes #879
- Use regular import of `effector` in ESM version of `effector-react`
This hack is presented only in `effector-react`, other bindings (`effector-vue` and `effector-solid`) works correctly without it. So, in #879 we've decided to remove it.
The solution is tested against playground-app in https://github.com/effector/next. I edited file `effector-react/effector-react.mjs` in `node_modules` of `playground_app`, cleaned `.next` and started the application, it is working as usual.

No magic import effector-react ESM

---

CHANGELOG.md
documentation/src/content/docs/en/api/effector-vue/useEvent.md
documentation/src/content/docs/en/api/effector-vue/useStore.md
documentation/src/content/docs/en/api/effector-vue/useUnit.md
documentation/src/content/docs/en/guides/migration-guide-v24.md
packages/effector-vue/composition.d.ts
src/vue/__tests__/useStore.test.ts
src/vue/lib/useDeprecate.ts
src/vue/useStore.ts

- Function `useStore` is deprecated in favor of `useUnit`
- Issue about future deletion https://github.com/effector/effector/issues/1100

Mark `useStore` in `effector-vue` as deprecated

---

CHANGELOG.md
documentation/src/content/docs/en/api/effector/fork.md
src/effector/__tests__/fork/fork.test.ts
src/effector/createEffect.ts
src/effector/fork/createScope.ts
src/effector/unit.h.ts

- Delete deprecated `fork({ handlers: sidMap })` overload

Delete plain object as handlers deprecated overload in fork

---

documentation/src/content/docs/en/introduction/examples.md

Убрал watch из примера Модального диалога, чтобы не прививать использование watch как инструмента связки и добавил overflow: auto чтобы верно показывать диалоговое окно.

remove watch from modal dialog example

---

CHANGELOG.md
packages/effector/index.d.ts
src/types/__tests__/effector/attach.test.ts

Allow `name` in `attach` when only passing `effect`

---

documentation/src/content/docs/en/api/effector-vue/ComponentOptions.md
documentation/src/content/docs/en/api/effector-vue/VueEffector.md
documentation/src/content/docs/en/api/effector-vue/VueEffectorVue2.md
documentation/src/navigation.ts
packages/effector-vue/options-vue3.d.ts
packages/effector-vue/options-vue3.ts
packages/effector-vue/package.json
tools/builder/packages.config.ts
tools/builder/rollup.ts
tsconfig.json

In this PR, the order of links in the Vue documentation has been changed, the documentation for the options api for vue 3 has been updated, links with low priority have been moved down, work has begun on exporting the options api for vue 3, this work needs to be completed and i need help)

fix: options api export from effector vue

---

documentation/src/content/docs/en/api/effector/split.md

There was no information in the description of the arguments that the fields in the cases object can be an array from Unit.

Update split.md: cases as an object with a field of type Unit<T>[]

---

documentation/src/content/docs/en/api/effector/swc-plugin.md

Update compatibility table after [release of `v0.6.0`](https://github.com/effector/swc-plugin/releases/tag/v0.6.0) of `@effector/swc-plugin`.

[docs] Update compatibility table for SWC v1.8.0

---

documentation/src/content/docs/en/api/effector/swc-plugin.md

Update SWC plugin documentation:
1. Update compatibility table up to current versions
2. Document a new HMR option
SWC plugin [changelog](https://github.com/effector/swc-plugin/blob/master/CHANGELOG.md#070)

[docs] Update SWC plugin documentation

---

packages/effector/index.d.ts
src/types/__tests__/effector/split.test.ts

This PR is similar to [this one](https://github.com/effector/effector/pull/1139) - it adds more explicit errors for split operator.
This PR solves next issues: #622, #769, #999 
I added some tests for match function inference, inline prepend calls and attach in default case.
Also i'm not sure about [narrower types edge cases](https://tsplay.dev/w2ykrW) - all highlighted cases must be an errors, but ts don't think so 🥲

Improve split type errors

---

packages/effector/index.d.ts

At present, it looks like the root `createStore` has `skipVoid` available, but `domain.createStore` warns/errors on undefined, but also doesn't list `skipVoid` amongst its possible config options. This PR adds that!

Add skipVoid to type of domain.createStore

---

documentation/src/content/docs/en/api/effector/swc-plugin.md
documentation/src/content/docs/ru/api/effector/swc-plugin.md

Updated both `en` and `ru` versions
- HMR option now matches that of `babel-plugin`
- Extended Next.js compatibility further
- Added `effector-action` as a default factory
- Fixed broken external links
Plugin release: [v0.8.0](https://github.com/effector/swc-plugin/releases/tag/v0.8.0)

[docs] Update SWC Plugin documentation for `v0.8.0` release
